// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmkplcwehinidasbwqaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ta3BsY3dlaGluaWRhc2J3cWF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MjA0MjksImV4cCI6MjA3MDI5NjQyOX0.ZaNtAGRfmMWlbx1c6U6ILXsWlauX9MhzIB3eQhZDKHE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});